version: "3"
networks:
  default:
    external:
      name: netarkivet-net
services:
  wrs:
    build: https://github.com/pyohei/docker-cgi-python.git
    ports:
      - "8883:80"
    volumes:
      - ./wrs/cgi-bin:/production/www/cgi-bin
      - ./wrs/testdata:/data
      - "bitmag_files:/kbhpillar"
volumes:
  bitmag_files: