version: "3"
#  dockerhost:
#        image: qoomon/docker-host
#        cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
#        #mem_limit: 4M
#        restart: on-failure
networks:
  default:
    external:
      name: netarkivet-net

volumes:
  bitmag_files:

services:
#  nasar:
#    build: nasapp
#    links:
#      - database
#      - ftp
#    depends_on:
#      - database
#      - mq
#      - ftp
#    environment:
#      - APP_LABEL=ArcRepository
#      - APP_CLASS=dk.netarkivet.archive.arcrepository.ArcRepositoryApplication
#      - CLASSPATH=/nas/lib/netarchivesuite-monitor-core.jar:/nas/lib/netarchivesuite-harvester-core.jar:/nas/lib/netarchivesuite-archive-core.jar
#      - REPLICA=SB
#      - LOCATION=S
#    command: ["/nas/wait-for-postgres.sh", "database", "--", "/docker-entrypoint.sh"]
  database:
    build: nasdb
    ports:
      - "6543:5432"
  nasgui:
    build: nasapp
    ports:
      - "8078:8078"
    links:
      - database
    depends_on:
      - database
      - mq
    environment:
      - APP_LABEL=GUIApplication
      - APP_CLASS=dk.netarkivet.common.webinterface.GUIApplication
      - CLASSPATH=/nas/lib/netarchivesuite-monitor-core.jar:/nas/lib/netarchivesuite-harvest-scheduler.jar:/nas/lib/netarchivesuite-harvester-core.jar:/nas/lib/netarchivesuite-archive-core.jar
    command: ["/nas/wait-for-postgres.sh", "database", "--", "/docker-entrypoint.sh"]
  nashjm:
      build: nasapp
      links:
       - mq
       - database
      environment:
        - APP_LABEL=HarvestJobManagerApplication
        - APP_CLASS=dk.netarkivet.harvester.scheduler.HarvestJobManagerApplication
        - CLASSPATH=/nas/lib/netarchivesuite-monitor-core.jar:/nas/lib/netarchivesuite-harvest-scheduler.jar
        - REPLICA=KB
        - LOCATION=K
      command: ["/nas/wait-for-postgres.sh", "database", "--", "/docker-entrypoint.sh"]
  nasharfocus:
      build: nasapp
      links:
         - mq
         - ftp
         - bus
      environment:
          - APP_LABEL=HarvestController_Focused
          - APP_CLASS=dk.netarkivet.harvester.heritrix3.HarvestControllerApplication
          - CLASSPATH=/nas/lib/netarchivesuite-monitor-core.jar:/nas/lib/netarchivesuite-heritrix3-controller.jar
          - REPLICA=KB
          - LOCATION=K
          - H3_CHANNEL=FOCUSED
      ports:
        - 8443
        ##- 5005:5005
      hostname: nasharfocus
      command: ["/nas/wait-for-postgres.sh", "database", "--", "/docker-entrypoint.sh"]
#  nasharsnap:
#      build: nasapp
#      links:
#         - mq
#         - ftp
#         - bus
#      environment:
#          - APP_LABEL=HarvestController_Snapshot
#          - APP_CLASS=dk.netarkivet.harvester.heritrix3.HarvestControllerApplication
#          - CLASSPATH=/nas/lib/netarchivesuite-monitor-core.jar:/nas/lib/netarchivesuite-heritrix3-controller.jar
#          - REPLICA=KB
#          - LOCATION=K
#          - H3_CHANNEL=SNAPSHOT
#      ports:
#        - 8443
#      command: ["/nas/wait-for-postgres.sh", "database", "--", "/docker-entrypoint.sh"]
  nasidx:
        build: nasapp
        links:
           - mq
           - bus
           - cleaner
           - ftp
        environment:
            - APP_LABEL=IndexServer
            - APP_CLASS=dk.netarkivet.harvester.indexserver.IndexServerApplication
            - CLASSPATH=/nas/lib/netarchivesuite-monitor-core.jar:/nas/lib/netarchivesuite-harvest-scheduler.jar:/nas/lib/netarchivesuite-archive-core.jar
            - REPLICA=KB
            - LOCATION=K
        volumes:
        - "bitmag_files:/kbhpillar"
        depends_on:
          - cleaner
        command: ["/nas/wait-for-postgres.sh", "database", "--", "/nas/wait_for_exit.sh", "cleaner", "/docker-entrypoint.sh"]
  naswbindexer:
        build: nasapp
        links:
           - database
           - mq
           - bus
           - cleaner
        environment:
            - APP_LABEL=WaybackIndexerApplication
            - APP_CLASS=dk.netarkivet.wayback.indexer.WaybackIndexerApplication
            - CLASSPATH=/nas/lib/netarchivesuite-monitor-core.jar:/nas/lib/netarchivesuite-archive-core.jar:/nas/lib/netarchivesuite-wayback-indexer.jar
            - REPLICA=KB
            - LOCATION=K
            - NAS_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
        volumes:
        - "bitmag_files:/kbhpillar"
        ports:
          - 5005:5005
        depends_on:
          - cleaner
        command: ["/nas/wait-for-postgres.sh", "database", "--", "/nas/wait_for_exit.sh", "cleaner", "/docker-entrypoint.sh"]
#  nasvp:
#        build: nasapp
#        links:
#           - mq
#           - ftp
#        environment:
#            - APP_LABEL=ViewerProxyApplication
#            - APP_CLASS=dk.netarkivet.viewerproxy.ViewerProxyApplication
#            - CLASSPATH=/nas/lib/netarchivesuite-monitor-core.jar:/nas/lib/netarchivesuite-harvest-scheduler.jar:/nas/lib/netarchivesuite-archive-core.jar
#            - REPLICA=KB
#            - LOCATION=K
#        ports:
#          - 8878:8078
#        command: ["/nas/wait-for-postgres.sh", "database", "--", "/docker-entrypoint.sh"]
  cleaner:
      build: nasapp
      links:
          - bus
      command: ["/nas/wait_for_it.sh", "bus:61616", "--", "/nas/clearBitmag.sh"]
  mq:
    image: seges/openmq
    ports:
      - 7676
  ftp:
    build: docker-proftpd
    ports:
      - 20
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - USERNAME=jms
      - PASSWORD=jms*ftp