# Run with U_ID=$(id -u) G_ID=$(id -g) docker-compose -f docker-compose-bitmag.yml up
version: "3"
networks:
  default:
    external:
      name: netarkivet-net
services:
  bus:
    image: webcenter/activemq:5.12.0
    ports:
      - 61616
      - 8161:8161
    environment:
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
    command: ["/opt/activemq/bin/activemq", "console"]
  dav:
    #build: webdav
    image: blekinge/apache_webdav:latest
    ports:
      - 80
    userns_mode: "host"
  #  environment:
  #    - uid=$U_ID
  #    - gid=$G_ID
  #  volumes:
  #    - /home/csr/dav:/site/dav
  tomcat:
    image: tomcat:8
    volumes:
      - ./bitmag-conf/contexts:/usr/local/tomcat/conf/Catalina/localhost
      - ./bitmag-conf/wars:/wars
      - ./tomcat_logs:/usr/local/tomcat/logs
      - ./bitmag-conf/service-conf/:/service-conf
    ports:
      - 8180:8080
    depends_on:
      - bus
      - dav
#  file1pillar:
#    build: filepillar
#    volumes:
#     # - /home/csr/projects/docker-csr/bitmag/bitrepository-quickstart/var/pillar:/filedir
#      - "bitmag_files:/filedir"
#    depends_on:
#      - bus
#      - dav
#    ports:
#      - 22
  kb-pillar:
    build: kb-pillar
    volumes:
      - "bitmag_files:/kbhpillar"
    depends_on:
      - bus
      - dav
    tty: true
    stdin_open: true
    command: ["/kb-pillar/bin/wait_for_it.sh", "bus:61616", "--", "/kb-pillar/bin/kb-pillar", "start"]
    ##command: ["sleep", "1d"]
volumes:
  bitmag_files:
