version: "3"
networks:
  default:
    external:
      name: netarkivet-net
services:
  #wrs:
  #  ##build: https://github.com/pyohei/docker-cgi-python.git
  #  build: wrs
  #  ports:
  #    - "8883:80"
  #  volumes:
  #    - ./wrs/cgi-bin:/production/www/cgi-bin
  #    - ./wrs/testdata:/data
  #    - "bitmag_files:/netarkivet"
  #    - "fileresolverdb:/db"
  fileresolver:
    build: fileresolver
    ports:
      - "8884:80"
    volumes:
      - ./fileresolver/cgi-bin:/production/www/cgi-bin
      - "fileresolverdb:/db"
  fileresolverdb:
    build:
      context: fileresolverdb
      args:
        TESTFILES: "true"
    volumes:
      - "bitmag_files:/netarkivet"
      - "fileresolverdb:/db"
  wrs-https:
    build: wrs-https
    ports:
      - "8883:80"
      - "10443:10443"
    volumes:
      - ./wrs/cgi-bin:/production/www/cgi-bin
      - ./wrs/testdata:/data
      - "bitmag_files:/netarkivet"
      - "fileresolverdb:/db"
volumes:
  bitmag_files:
  fileresolverdb: